MODEL_NAME = "meta-llama/Llama-3.2-3B"
EMBEDDING_MODEL = "lokeshch19/ModernPubMedBERT"
CROSS_ENCODER = "ncbi/MedCPT-Cross-Encoder"
RETRIEVAL_K = 10
MMR_J = 15
FINAL_N = 10
MMR_LAMBDA = 0.2
TEMPERATURE = 0.2
QUANT=True
MODEL_QUANT="Mistral-7B-Instruct-v0.3-Q6_K.gguf"
REPO="bartowski/Mistral-7B-Instruct-v0.3-GGUF"
